version: "3.3"
services:

  worker:
    build:
      context: ./worker
      dockerfile: Dockerfile
  
  scheduler:
    build:
      context: ./scheduler
      dockerfile: Dockerfile
  
  api-prod:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod