"""Added source specific fields to doc table

Revision ID: 9a51fa55fef2
Revises: 6b7e80293a87
Create Date: 2022-07-03 01:43:47.407046

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a51fa55fef2'
down_revision = '6b7e80293a87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document', sa.Column('doc_id', sa.String(), nullable=True))
    op.add_column('document', sa.Column('doc_last_updated', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document', 'doc_last_updated')
    op.drop_column('document', 'doc_id')
    # ### end Alembic commands ###